const Constants = {
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',

    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
    SHOW_ALL: 'SHOW_ALL',

    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',

    FETCH_ALL_REQUEST: 'Characters.FETCH_ALL_REQUEST',
    FETCH_ALL_SUCCESS: 'Characters.FETCH_ALL_SUCCESS',
    FETCH_ALL_FAILURE: 'Characters.FETCH_ALL_FAILURE',
}

export default Constants;